version: "3"
services:
    app:
        build:
            context: ./app
        environment:
            - QQ=123456789
    web:
        depends_on:
            - app
        build:
            context: ./web
        ports:
            - "80:80"